### ISSUE TITLE
not working 1.20.4

### ISSUE THREAD

**Issue by TheVoado555** [Viola-Siemens/Mod-Whitelist#2]
when trying to start a server with this mod and only fabric api server 1.20.4 crashes

**Comment by Viola-Siemens** [comment]
> when trying to start a server with this mod and only fabric api server 1.20.4 crashes

any log or output?

**Comment by TheVoado555** [comment]
https://mclo.gs/VRB1LJB

**Comment by TheVoado555** [comment]
Thanks, really like your mod, no one has done this before, appreciate it!

**Comment by Viola-Siemens** [comment]
Thanks for supporting. New version is now uploaded, you can download it from curseforge or modrinth.
