### ISSUE TITLE
[Question] I need some clarification about the description

### ISSUE THREAD

**Issue by wtlgo** [Viola-Siemens/Mod-Whitelist#3]
> In addition, if USE_WHITELIST_ONLY is true, CLIENT_MOD_BLACKLIST field is just ignored while running the server. And if USE_WHITELIST_ONLY is true, CLIENT_MOD_WHITELIST field is ignored instead.

What does this mean?

**Comment by Viola-Siemens** [comment]
For example, here's a configuration file:
```json
{
	"USE_WHITELIST_ONLY": false,
	"CLIENT_MOD_NECESSARY": [
		"mod_whitelist",
		"jei"
	],
	"CLIENT_MOD_WHITELIST": [
		"fabricloader",
		"java",
		"mod_whitelist"
	],
	"CLIENT_MOD_BLACKLIST": [
		"aristois",
		"bleachhack"
	]
}
```
Now `USE_WHITELIST_ONLY` is false, so `CLIENT_MOD_WHITELIST` field is ignored - it's blacklist mode. If client players install `aristois` or `bleachhack`, they will not be allowed to enter this server, and they will receive information to uninstall mods on the blacklist.

Here's another configuration file:
```json
{
	"USE_WHITELIST_ONLY": true,
	"CLIENT_MOD_NECESSARY": [
		"mod_whitelist",
		"jei"
	],
	"CLIENT_MOD_WHITELIST": [
		"forge",
		"minecraft",
		"java",
		"mod_whitelist",
		"jei",
		"villagerarmor",
		"emeraldcraft",
		"terrablender"
	],
	"CLIENT_MOD_BLACKLIST": [
		"aristois",
		"bleachhack"
	]
}
```
Now `USE_WHITELIST_ONLY` is true, so `CLIENT_MOD_BLACKLIST` field is ignored - it's whitelist mode. If client players install any other mods that are not in `CLIENT_MOD_WHITELIST`, for example, `appleskin`, they will receive information to uninstall `appleskin` and are not allowed to enter this server.

In addition, `CLIENT_MOD_NECESSARY` contains required mods that should be installed whether it is whitelist or blacklist mode. In these two configs above, `jei` is a necessary mod that client players MUST install.

**Comment by wtlgo** [comment]
Ah, so it must be a typo because it says

> In addition, if **USE_WHITELIST_ONLY is true**, CLIENT_MOD_BLACKLIST field is just ignored while running the server. And if **USE_WHITELIST_ONLY is true**, CLIENT_MOD_WHITELIST field is ignored instead.

**Comment by Viola-Siemens** [comment]
> Ah, so it must be a typo because it says
> 
> > In addition, if **USE_WHITELIST_ONLY is true**, CLIENT_MOD_BLACKLIST field is just ignored while running the server. And if **USE_WHITELIST_ONLY is true**, CLIENT_MOD_WHITELIST field is ignored instead.

my bad, that's a typo

**Comment by wtlgo** [comment]
Still thanks for clarification :^)
