### ISSUE TITLE
根本没法用

### ISSUE THREAD

**Issue by Leoparking** [Viola-Siemens/Mod-Whitelist#6]
[crash-2024-07-15_15.17.44-fml.txt](https://github.com/user-attachments/files/16231133/crash-2024-07-15_15.17.44-fml.txt)

**Comment by Leoparking** [comment]
<img width="866" alt="image" src="https://github.com/user-attachments/assets/5be8c952-3dc5-48f9-814c-f2fd4144d6df">

**Comment by Viola-Siemens** [comment]
你配置文件格式错了

**Comment by Viola-Siemens** [comment]
The configuration file is invalid after questioner's wrongly edited. So this issue is closed.
