### ISSUE TITLE
Uninstall mod "minecraft"

### ISSUE THREAD

**Issue by kight11** [Viola-Siemens/Mod-Whitelist#9]
<img width="886" alt="da faq" src="https://github.com/user-attachments/assets/af079e9b-629d-43c8-973c-6bbfe31bae20">
Hello,
After Mod whitelist is installed, this massage appeared.
I've checked the mod file, game version, forge version, all matching between server and client. Any help please

**Comment by Viola-Siemens** [comment]
Edit your server-side config, add "minecraft" to `CLIENT_MOD_WHITELIST` field.

**Comment by Viola-Siemens** [comment]
btw, if you are server operator, it is recommended to open your client-side latest.log, you will find the following message:
```
Mod Whitelist v0.0.0 from the client! Modlist: ["fabric-api", "fabric-api-base", ...]
```
you can copy the modlist to the `CLIENT_MOD_WHITELIST` field of your server-side config to simplify the configuration step.

**Comment by kight11** [comment]
Just tried, it worked well. You, Viola-Siemens, are my saviour, I'm eternally thankful.
